---
- name: Create Temp Build Directory for HAProxy
  file:
    path: "{{ playbook_dir }}/output"
    state: directory

- name: "Drop necessary templates into output folder"
  template:
    src: templates/{{ item.src }}.j2
    dest: "{{ playbook_dir }}/output/{{ item.src }}"
    mode: 0664
  loop:
    - src: haproxy-backup.fcc
    - src: haproxy-master.fcc
    - src: haproxy.cfg
    - src: keepalived-master.conf
    - src: keepalived-backup.conf
...