---

lb_ssh_key:
  - key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
  - key: "{{ lookup('file', '/home/user2/.ssh/id_rsa.pub') }}"
lb_vm:
  name: lb
  ipaddr: 10.0.0.200
  cidr: 22
net:
  interface: eth0
bootstrap_vm:
  name: bootstrap
  ipaddr: 10.0.0.210
master_vms:
  - { name: "master1", ipaddr: "10.0.1.1"}
  - { name: "master2", ipaddr: "10.0.1.2"}
  - { name: "master3", ipaddr: "10.0.1.3"}
# worker_vms:
#   - { name: "worker1", ipaddr: "10.0.1.20"}
#   - { name: "worker2", ipaddr: "10.0.1.21"}
